### PR TITLE
Remove pycache

### PR DESCRIPTION
**Pull request by JohnScolaro**
Pycache files in repo = bad.

### CODE REVIEW

**Review by JohnScolaro — COMMENTED** [review]
Remove pycache

**Review by calumacutt — APPROVED** [review]
Bet

**Comment by william-allen-harris** [comment]
But pycach == speed

**Comment by william-allen-harris** [comment]
Let's take a helicopter approach to solving this issue. While having a look under the bonnet it's evident that the pycache files are disgusting and should never be commit to remote. Let's go ahead and add in pycache to our gitignore file to get ride of these pesky buggers. It's a low handing fruit solution but we can run it up the flagpole if you like. Let me know if you want to touch base offline about this other wise have an idea shower to se Eid you agree. I'm out of bandwidth at the moment, would you be able to implement this please @JohnScolaro? If so, don't let the grass grow to long on this one otherwise stack-holders might get a bit frustrated. Great work team keep it up.

**Comment by JohnScolaro** [comment]
Are you gonna merge this or what bruh

**Pull request merged**
